// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import { FC, ReactNode} from 'react';
import Head from 'next/head';
// import { Header } from '../modules/header';

const Layout: FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <>
            {/* <Header /> */}
            <main>{children}</main>
        </>
    )
} 

export default Layout;
